const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const compiled = ts.transpileModule(fs.readFileSync(require.resolve('./src/services/visualAnalysis.ts'), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const mod = new Module('visualAnalysis'); mod._compile(compiled, 'visualAnalysis.js');
const { cameraWarningIssue, measureMouthOpening, measureVisualSample, measureHandPose } = mod.exports;
const sample = {timestamp:0,facing:true,positioned:true,head:[0,0],wrists:[],distance:null};
assert.equal(cameraWarningIssue(sample), null);
assert.equal(cameraWarningIssue({...sample,distance:'close'}), 'close');
assert.equal(cameraWarningIssue({...sample,facing:false}), 'away');
assert.equal(cameraWarningIssue({...sample,mouthOpeningRatio:.35}), null);
assert.equal(cameraWarningIssue({...sample,mouthOpeningRatio:.95}), 'expression');
assert.equal(cameraWarningIssue({...sample,facing:null,mouthOpeningRatio:null}), null);
assert.equal(cameraWarningIssue({...sample,issue:'dark',facing:false}), 'dark');
assert.equal(measureMouthOpening([]), null);
const points=[];points[61]={x:.4,y:.5};points[291]={x:.6,y:.5};points[13]={x:.5,y:.45};points[14]={x:.5,y:.55};
assert.ok(Math.abs(measureMouthOpening(points)-.5)<.001);
const pose=[];
const point=(x,y)=>({x,y,z:0,visibility:.99});
pose[0]=point(.5,.3);pose[7]=point(.41,.3);pose[8]=point(.59,.3);
pose[11]=point(.3,.65);pose[12]=point(.7,.65);
assert.equal(measureVisualSample(pose,0).shouldersVisible,true);
pose[11]=point(.3,.97);
assert.equal(cameraWarningIssue(measureVisualSample(pose,0)),'shoulders');
pose[11]=point(.3,.65);pose[7]=point(.455,.3);pose[8]=point(.545,.3);
assert.equal(measureVisualSample(pose,0).distance,'far');
pose[12]={...point(.7,.65),visibility:.2};
assert.equal(measureVisualSample(pose,0).shouldersVisible,false);
const hand=(extended)=>{
  const p=Array.from({length:21},()=>({x:.5,y:.7,z:0}));
  p[0]={x:.5,y:.8,z:0};
  for(const [i,base] of [5,9,13,17].entries()) {
    const x=.38+i*.08;
    const ys=extended.includes(base)?[.6,.5,.4,.3]:[.6,.5,.55,.64];
    ys.forEach((y,j)=>p[base+j]={x,y,z:0});
  }
  return p;
};
assert.equal(measureHandPose(hand([9])),'middle-finger');
assert.equal(measureHandPose(hand([5,17])),'horns');
const victory=hand([5,9]);victory[8].x-=.04;victory[12].x+=.04;
assert.equal(measureHandPose(victory),'victory');
assert.equal(measureHandPose(hand([5,9,13,17])),null);
assert.equal(measureHandPose(hand([])),null);
assert.equal(measureHandPose([]),null);
assert.equal(measureHandPose(hand([9]).map(p=>({...p,x:1-p.x}))),'middle-finger');
assert.equal(cameraWarningIssue({...sample,handPose:'middle-finger'}),'hand-pose');
assert.equal(cameraWarningIssue({...sample,handPose:'horns',issue:'dark'}),'dark');
const cropped=hand([9]);cropped[12].x=1.1;
assert.equal(measureHandPose(cropped),null);
const heart=hand([]);heart[8]={x:.38,y:.55,z:0};heart[4]={x:.39,y:.55,z:0};
assert.equal(measureHandPose(heart),'finger-heart');
console.log('24 camera warning checks passed');
