const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const compiled = ts.transpileModule(fs.readFileSync(require.resolve('./src/services/speechEndpoint.ts'), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const mod = new Module('speechEndpoint'); mod._compile(compiled, 'speechEndpoint.js');
const update = mod.exports.updateSpeechEndpoint;
const fresh = () => ({ speechStartedAt: null, silenceStartedAt: null });
let state = fresh();
assert.equal(update(state, 0, 0), false);
assert.equal(update(state, 0, 60000), false);
update(state, .04, 0); update(state, 0, 200);
assert.equal(update(state, 0, 1799), false);
assert.equal(update(state, 0, 1800), true);
state = fresh(); update(state, .04, 0); update(state, 0, 1000);
update(state, .04, 2000); update(state, 0, 2100);
assert.equal(update(state, 0, 2600), false);
assert.equal(update(state, 0, 3700), true);
state = fresh(); update(state, .04, 0);
assert.equal(update(state, .04, 6000), false);
console.log('7 speech endpoint checks passed: no speech, short answer, pause/resume, continuous speech');
